services:
  - type: web
    name: rollpoint-shop
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STORE_NAME
        value: RollPoint
      - key: STORE_EMAIL
        value: malikusmanhaider0346@gmail.com
      - key: STORE_ADDRESS
        value: "Rehmat Plaza, Pakistan Town Phase 2 Rd, near Allah Wali Masjid, Phase 2 Islamabad, 45720, Pakistan"
      - key: GOOGLE_MAPS_URL
        value: "https://maps.app.goo.gl/N9xDnGzuN3n8PbCD6?g_st=awb"
      - key: WHATSAPP_NUMBER
        value: "03089134302"
      - key: WHATSAPP_INTL
        value: "923089134302"
      - key: FLAT_SHIPPING_RATE
        value: "250"
      - key: CLIENT_URL
        value: "*"
